### ISSUE TITLE
Setup ManagerApp

### ISSUE THREAD

**Issue by Koufan-De-King** [ADORSYS-GIS/webank-AppManager#2]
## Setup ManagerApp:

**Initialize the ManagerApp frontend using React and TypeScript.**
**Integrate PWA support with Vite for offline functionality.**
**Ensure project is properly configured and ready for further development.**

**Comment by francis-pouatcha** [comment]
Why don't we have a link to the branch?

**Comment by NkwaTambe** [comment]
Hi mr  @francis-pouatcha ,

The reason there’s no link to the branch is that I created it locally, not directly from GitHub. I'll push it and ensure the link is available for future tickets. Thanks for pointing it out!
